### ISSUE TITLE
Releasing model outputs

### ISSUE THREAD

**Issue by peteanderson80** [jialuli-luka/EnvEdit#2]
Hi Jialu,

Great paper! 

I was wondering if you would consider sharing the model outputs (predicted paths) for RxR val-unseen and R2R val-unseen? This would be useful to dig into the performance in more detail. Sharing the outputs of your agent saves some time and avoids randomness compared to re-training the agent from scratch.

Cheers,
Peter

**Comment by jialuli-luka** [comment]
Hi Peter,

Thanks for your interest in EnvEdit! You can access the model outputs from this [link](https://www.dropbox.com/sh/hp7x16t1vwxtpko/AAAALROM3sKaCU4b9Xv8ag-5a?dl=0). These outputs are from the models we use to submit to R2R and RxR leaderboard. Please let me know if you need trained model/model outputs of other models.

Best,
Jialu

**Comment by peteanderson80** [comment]
Thanks Jialu, this is super helpful!
